apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  postgresVersion: {{ .Values.postgresVersion }}
  openshift: {{ .Values.openshift }}
  instances:
    - name: {{ .Values.instances.name }}
      replicas: {{ .Values.instances.replicas }}
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.instances.dataVolumeClaimSpec.storage }}
        storageClassName: {{ .Values.instances.dataVolumeClaimSpec.storageClassName }}
  proxy:
    pgBouncer:
      replicas: {{ .Values.proxy.pgBouncer.replicas }}
  pgBackRest:
    repos:
      - name: repo1
        enabled: {{ .Values.pgBackRest.repo1.enabled }}
  monitoring:
    pgmonitor:
      enabled: {{ .Values.pgmonitor.enabled }}
