fullnameOverride: crunchy-postgres

postgresVersion: 15
openshift: true

instances:
  name: test
  replicas: 2
  dataVolumeClaimSpec:
    storage: 2Gi
    storageClassName: netapp-block-standard

pgBackRest:
  repo1:
    enabled: true

proxy:
  pgBouncer:
    replicas: 2

pgmonitor:
  enabled: true
